### ISSUE TITLE
libpsl.so.5 is not linked

### ISSUE THREAD

**Issue by seisman** [savage13/pssac2#5]
```
$ make
make  all-recursive
make[1]: Entering directory `/home/seisman/Desktop/workspace/pssac2'
Making all in t
make[2]: Entering directory `/home/seisman/Desktop/workspace/pssac2/t'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/seisman/Desktop/workspace/pssac2/t'
make[2]: Entering directory `/home/seisman/Desktop/workspace/pssac2'
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra `gmt-config --cflags`  -c -o pss.o pss.c
pss.c: In function ‘pssac2_plot_scale’:
pss.c:474:3: warning: implicit declaration of function ‘asprintf’ [-Wimplicit-function-declaration]
   asprintf(&buffer, "-R%s -J%s -bi -bo -<%s  ->%s ", R->arg, J->arg, i_string, o_string);
   ^
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra `gmt-config --cflags`  -c -o jb.o jb.c
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra `gmt-config --cflags`  -c -o sacio.o sacio.c
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra `gmt-config --cflags`  -c -o array.o array.c
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra `gmt-config --cflags`  -c -o gmt_support.o gmt_support.c
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra `gmt-config --cflags`  -c -o clip.o clip.c
gcc -Wall -Wextra `gmt-config --cflags`  `gmt-config --libs`  -o pssac2 pss.o jb.o sacio.o array.o gmt_support.o clip.o  -lm 
/usr/bin/ld: warning: libpsl.so.5, needed by /opt/GMT-5.1.1/lib64/libgmt.so, not found (try using -rpath or -rpath-link)
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_loadimage'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setcolor'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plottext'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_beginlayer'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setorigin'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_defunits'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_settransparencymode'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plottextclip'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_defpen'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_fopen'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `psl_gray_encode'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setparagraph'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setmiterlimit'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_beginclipping'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_command'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `psl_iz'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_defcolor'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plottextpath'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotsegment'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_beginplot'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setdefaults'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_comment'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_deftextdim'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `New_PSL_Ctrl'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_free_nonmacro'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_beginsession'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotarc'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plottextbox'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotpolygon'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setfont'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotbitimage'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotparagraph'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_endsession'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setpattern'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotparagraphbox'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotsymbol'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setlinewidth'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setdash'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_endclipping'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setformat'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotepsimage'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setlinejoin'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setfill'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotbox'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_setlinecap'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_endlayer'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_endplot'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotpoint'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotcolorimage'
/opt/GMT-5.1.1/lib64/libgmt.so: undefined reference to `PSL_plotline'
collect2: error: ld returned 1 exit status
make[2]: *** [pssac2] Error 1
make[2]: Leaving directory `/home/seisman/Desktop/workspace/pssac2'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/seisman/Desktop/workspace/pssac2'
make: *** [all] Error 2
```

This error shows because the `libpsl.so.5` is NOT linked. 

This seems to be a bug of `gmt-config`:

```
$ gmt-config --libs
-L/opt/GMT-5.1.1/lib64 -lgmt
```

the correct output should be 

```
-L/opt/GMT-5.1.1/lib64 -lgmt -lpsl
```

**Comment by savage13** [comment]
Moved gmt-config --libs to end of link line. Should be fixed.

**Comment by seisman** [comment]
I don't know why it still does not work for me.

I have report a issue on GMT: http://gmt.soest.hawaii.edu/issues/635
